package main

import (
	_ "github.com/serter95/centralServiceBackendGo/docs" // docs is generated by Swag CLI, you have to import it.

	"github.com/gorilla/mux"
	httpSwagger "github.com/swaggo/http-swagger"
)

func routes(router *mux.Router) {
	router.HandleFunc("/search/{criteria}", searchData).Methods("GET")
	// Swagger
	router.PathPrefix("/swagger").Handler(httpSwagger.WrapHandler)
}
