basePath: /
definitions:
  main.StandardResponse:
    properties:
      author:
        type: string
      category:
        type: string
      name:
        type: string
      origin:
        type: string
      previewUrl:
        type: string
    type: object
host: localhost:3000
info:
  contact:
    email: steran@tribalworldwide.gt
    name: Sergei Teran
  description: Central Service API that consume 3 direfent services
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Central Service API
  version: "1.0"
paths:
  /search/{criteria}:
    get:
      consumes:
      - application/json
      description: search criteria in all services
      parameters:
      - description: criteria that you want to find
        in: path
        name: criteria
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/main.StandardResponse'
            type: array
      summary: search criteria in all services
      tags:
      - search
swagger: "2.0"
